docs: Include direction to apply the global manifest. (#1196)
When I tried to follow the steps in this file I ended up with:
```
Error from server (NotFound): configmaps "global" not found
ERROR: 21:06:18 - g3k_manifest_path could not establish commons hostname
dirname: missing operand
Try 'dirname --help' for more information.
```

Adding this step (borrowed from the CSOC-attached directions) fixed this issue.